version: '3'

services:
  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres_djangoproject
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #command: bash -c "docker exec -it small_django_project_postgres_1 bash"
    #command: bash -c "docker exec -it small_django_project_postgres_1 sudo -u postgres psql"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: lemissan@atonra.ch
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always


  redis:
    image: redis
    ports:
    - "6379:6379"
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  celery:
    build: .
    command: celery -A djangoproject worker -l info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
  celery-beat:
    build: .
    command: celery -A djangoproject beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: