version: '3'

services:
  db:
    image: postgres
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD= "trust"
    command: psql createdb postgres_djangoproject
  redis:
    image: redis
    ports:
    - "6379:6379"
  celery:
    build: .
    command: celery -A djangoproject worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A djangoproject beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - redis
  web:
    working_dir: /app
    build: .
    command: ls
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data: