version: '3'

services:
  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    # volumes:
      # - postgres_data:/var/lib/postgresql/data/
      #- ~/DockerVolumes/postgres_djangoproject:/var/lib/postgresql/data/

  redis:
    image: redis
    ports:
    - "6379:6379"

volumes:
  postgres_data: