# Generated by Django 3.0.7 on 2020-06-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
