from enum import Enum

class ChoiceEnum(Enum):

    @classmethod
    def choices(cls):
        return [(choice.name, choice.value) for choice in cls]

    @classmethod
    def names(cls):
        return [choice.name for choice in cls]
    
    @classmethod
    def values(cls):
        return [choice.value for choice in cls]

    @classmethod
    def to_dict(cls):
        return {choice.name: choice.value for choice in cls}



class WBIcon(ChoiceEnum):
    FILTERS_OFF = "wb-icon-filters-off"
    COMPLETE_A_Z = "wb-icon-sort-a-z-complete"
    COMPLETE_Z_A = "wb-icon-sort-z-a-complete"
    DOLLAR = "wb-icon-dollar"
    DOCUMENT = "wb-icon-document"
    TRADE = "wb-icon-trade"
    BAR_CHART_RISING = "wb-icon-bar-chart-rising"
    SEND = "wb-icon-send"
    HOURGLASS_MIDDLE = "wb-icon-hourglass-middle"
    HOURGLASS_FULL = "wb-icon-hourglass-full"
    HOURGLASS_EMPTY = "wb-icon-hourglass-empty"
    CHAT = "wb-icon-chat"
    LOCK_OPEN = "wb-icon-lock-open"
    LOCK_CLOSED = "wb-icon-lock-closed"
    MENU = "wb-icon-menu"
    THUMBS_UP_EMPTY = "wb-icon-thumbs-up-empty"
    FOLDER_STACK = "wb-icon-folders-stack"
    SPEACH_BUBBLE = "wb-icon-speach-bubble"
    LUNCH = "wb-icon-lunch"
    CIRCLE_YES = "wb-icon-circle-yes"
    CIRCLE_NO = "wb-icon-circle-no"
    X_SMALL = "wb-icon-x-small"
    X = "wb-icon-x"
    GLOBE = "wb-icon-globe"
    THUMBS_DOWN = "wb-icon-thumbs-down"
    TIME_OFF_1 = "wb-icon-time-off-1"
    TIME_OFF_2 = "wb-icon-time-off-2"
    STAR = "wb-icon-star"
    SORT_A_Z = "wb-icon-sort-a-z"
    SORT_Z_A = "wb-icon-sort-z-a"
    SKYPE = "wb-icon-skype"
    COG = "wb-icon-cog"
    SEARCH = "wb-icon-search"
    FLOPPY_DISK = "wb-icon-floppy-disk"
    FLOPPY_DISK_SAVED = "wb-icon-floppy-disk-saved"
    ENVELOP = "wb-icon-envelop"
    ENVELOP_EURO = "wb-icon-envelop-euro"
    ENVELOP_LOCK = "wb-icon-envelop-lock"
    ENVELOP_OPEN = "wb-icon-envelop-open"
    ENVELOP_PERSON = "wb-icon-envelop-person"
    REFRESH = "wb-icon-refresh"
    PROPOSALS = "wb-icon-proposals"
    PORTFOLIO = "wb-icon-portfolio"
    PHONE = "wb-icon-phone"
    PERSON = "wb-icon-person"
    PEOPLE = "wb-icon-people"
    EYE = "wb-icon-eye-open"
    FLOPPY_DISK_NOT_SAVED = "wb-icon-floppy-disk-not-saved"
    BELL_FULL = "wb-icon-bell-full"
    BELL_EMPTY = "wb-icon-bell-empty"
    NOTES = "wb-icon-notes"
    NOTEBOOK = "wb-icon-notebook"
    NOMINALS = "wb-icon-nominals"
    TIMER = "wb-icon-timer"
    STEP_LEFT = "wb-icon-step-left"
    STEP_RIGHT = "wb-icon-step-right"
    MRS_RING = "wb-icon-mrs-ring"
    FEMALE = "wb-icon-female"
    MALE = "wb-icon-male"
    MINIMIZE = "wb-icon-minimize"
    MAXIMIZE = "wb-icon-maximize"
    PAPER = "wb-icon-envelope-paper"
    DISABLED = "wb-icon-disabled"
    LOCATION_PIN = "wb-icon-location-pin"
    SORT_A_Z_LITTLE_Z = "wb-icon-sort-a-z-little-z"
    SORT_Z_A_LITTLE_A = "wb-icon-dort-z-a-little-a"
    LIST = "wb-icon-list"
    THUMBS_UP = "wb-icon-thumbs-up-full"
    UNDO = "wb-icon-undo"
    FOLDER_EURO = "wb-icon-folder-euro"
    INFO = "wb-icon-info"
    GRAPH = "wb-icon-graph"
    STATS = "wb-icon-chart"
    FILTERS = "wb-icon-filters"
    ARROW_RIGHT = "wb-icon-arrow-right"
    ARROW_LEFT = "wb-icon-arrow-left"
    PENCIL = "wb-icon-pencil"
    TRASH = "wb-icon-trash"
    DATA = "wb-icon-data"
    DASHBOARD = "wb-icon-dashboard"
    BRIEFCASE = "wb-icon-briefcase"
    CLOCK = "wb-icon-clock"
    HANDS_EURO = "wb-icon-hands-shaking-euro"
    CAMERA_1 = "wb-icon-camera-1"
    CAMERA_2 = "wb-icon-camera-2"
    CALENDAR = "wb-icon-calendar"
    BOOKMARK = "wb-icon-bookmark"
    CAKE = "wb-icon-cake"
    BANK = "wb-icon-bank"
    FOLDER_PLUS = "wb-icon-folder-plus"
    MAN = "wb-icon-man"
    HANDS = "wb-icon-hands"
    TRIANGLES_RIGHT_STOP = "wb-icon-triangles-right-stop"
    TRIANGLES_LEFT_STOP = "wb-icon-triangles-left-stop"
    TRIANGLES_UP = "wb-icon-triangles-up"
    TRIANGLES_RIGHT = "wb-icon-triangles-right"
    TRIANGLES_LEFT = "wb-icon-triangles-left"
    TRIANGLES_DOWN = "wb-icon-triangles-down"
    TRIANGLE_UP = "wb-icon-triangle-up"
    TRIANGLE_LEFT = "wb-icon-triangle-left"
    TRIANGLE_DOWN = "wb-icon-triangle-down"
    TRIANGLE_RIGHT = "wb-icon-triangle-right"
    PLUS = "wb-icon-plus"
    REPLACE = "wb-icon-replace"