version: '3'

services:
  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASS=root
      - POSTGRES_DB=postgres_djangoproject
      - POSTGRES_HOST_AUTH_METHOD= "trust"
      - POSTGRES_PORT=5432
    # volumes:
      # - postgres_data:/var/lib/postgresql/data/
      #- ~/DockerVolumes/postgres_djangoproject:/var/lib/postgresql/data/
    
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
        - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: lemissan@atonra.ch
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always

  redis:
    image: redis
    ports:
    - "6379:6379"
  web:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  celery:
    build: .
    command: celery -A djangoproject worker -l info
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis
  celery-beat:
    build: .
    command: celery -A djangoproject beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: