name: Continious Integration
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: project-db
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pipenv install --dev
    - name: Testing
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run pytest -v --cache-clear djangoapp/tests/
      env:
        DATABASE_URL: postgres://root:root@localhost:5432/project-db
    - uses: codecov/codecov-action@v1
      with:
        name: Uploading Coverage Report to Codecov
        token: ${{ secrets.CODECOV_TOKEN }}