name: Continious Integration
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: project-db
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
    - uses: actions/cache@v1
      id : cache-venv
      with:
        path: ./.venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      uses: dschep/install-pipenv-action@v1
      run: |
        pipenv lock --dev --requirements > requirements.txt
        python -m venv ./.venv 
        . ./.venv/bin/activate
        pip install -r requirements.txt
    - name: Testing
      run: |
        # pipenv run pytest -v --cache-clear */tests/
        . ./.venv/bin/activate 
        pytest -v */tests/
      env:
        DATABASE_URL: postgres://root:root@localhost:5432/project-db
    - uses: codecov/codecov-action@v1
      with:
        name: Uploading Coverage Report to Codecov
        token: ${{ secrets.CODECOV_TOKEN }}